# Assignment 1
**You need to work with numpy library. Write code and perform computations in the cells below. There are nine questions.** 

In [32]:
import numpy as np

__1. Create a one-dimensional array with 10 elements containing numbers from 1 to 10. Display the sum of all elements and their average value.__

In [35]:
arr1 = np.arange(1, 11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
sum1 = np.sum(arr1)
sum1

55

In [39]:
avg1 = np.mean(arr1)
avg1

5.5

__2. Create an array of numbers from 10 to 50 with a step of 5. Display the elements of the array that are greater than 20 and less than 40.__

In [42]:
arr2 = np.arange(10, 51, 5)
arr2

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [44]:
arr2[(arr2 > 20) & (arr2 < 40)]

array([25, 30, 35])

__3. Create a 5x5 matrix with row values ranging from 0 to 4__

In [46]:
arr3 = np.zeros((5, 5)) + np.arange(5)
arr3

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

__4. Create a random vector of size 10 and sort it__

In [49]:
arr4 = np.sort(np.random.rand(10))
arr4

array([0.02566389, 0.09139637, 0.13756762, 0.24201154, 0.33992175,
       0.40703118, 0.42610807, 0.52897186, 0.58910097, 0.75063069])

__5. Create a 3x3 two-dimensional array filled with random numbers. Multiply it by a scalar 2 and display the result.__

In [54]:
arr5 = np.random.rand(3,3) * 2
arr5

array([[0.41362239, 0.53245244, 0.24251909],
       [1.60849742, 1.63279306, 0.26130252],
       [1.47835431, 0.49768936, 1.92808096]])

__6. Consider two random array A and B, check if they are equal__

In [57]:
arr6_A = np.random.rand(10)
arr6_B = np.random.rand(10)
print(arr6_A)
print(arr6_B)
np.array_equal(arr6_A, arr6_B)

[0.41609437 0.80924921 0.1690109  0.00359777 0.65493416 0.32674858
 0.94105009 0.59671374 0.69889523 0.0701504 ]
[0.60341137 0.80458244 0.39270505 0.74314273 0.31453847 0.94693679
 0.40797362 0.08614424 0.91787515 0.77858151]


False

__7. Create a random matrix and swap two rows of an array?__

In [60]:
arr7 = np.random.rand(5,5)
arr7

array([[0.73718118, 0.5504097 , 0.97765826, 0.09116691, 0.45886756],
       [0.6214208 , 0.06939626, 0.30473421, 0.98648084, 0.25950966],
       [0.29121868, 0.92517666, 0.22479052, 0.33460432, 0.28633082],
       [0.9904241 , 0.48101756, 0.71744413, 0.25411886, 0.93608169],
       [0.03018112, 0.52001219, 0.57163669, 0.32257101, 0.48307075]])

In [11]:
temp7 = arr7[0].copy()
arr7[0] = arr7[1]
arr7[1] = temp7
arr7

array([[0.94160335, 0.12108892, 0.81945632, 0.45979315, 0.35949115],
       [0.58583276, 0.83673556, 0.44109779, 0.85935643, 0.13113911],
       [0.54343897, 0.28028122, 0.86260807, 0.36088387, 0.09032512],
       [0.41959015, 0.08569753, 0.37964362, 0.13846197, 0.53867322],
       [0.31260264, 0.87632514, 0.68913713, 0.6189627 , 0.482598  ]])

__8. Create two matrices of size 2x2: one with values from 1 to 4, and the other from 5 to 8. Find the sum and the product of these matrices.__

In [14]:
arr8_1 = np.array([[1, 2], [3, 4]])
arr8_2 = np.array([[5, 6], [7, 8]])
print(arr8_1)
print(arr8_2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [29]:
# sum8 = arr8_1 + arr8_2
sum8 = np.add(arr8_1, arr8_2)
sum8

array([[ 6,  8],
       [10, 12]])

In [18]:
product8 = arr8_1 * arr8_2
product8

array([[ 5, 12],
       [21, 32]])

__9. Create an array of 15 random integers in the range from 1 to 100. Replace all elements greater than 50 with 0.__

In [21]:
arr9 = np.random.randint(1, 101, 15)
arr9

array([24,  9, 94, 52, 81, 40,  5,  8, 10, 97, 39,  8, 86, 19, 19])

In [23]:
arr9[arr9 > 50] = 0
arr9

array([24,  9,  0,  0,  0, 40,  5,  8, 10,  0, 39,  8,  0, 19, 19])